// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RMK.Infra.Data.Context;

#nullable disable

namespace RMK.Infra.Data.Migrations
{
    [DbContext(typeof(RMKContext))]
    partial class RMKContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RMK.Domain.Models.Account.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ادمین",
                            RoleName = "admin_role"
                        },
                        new
                        {
                            Id = 2,
                            Name = "کاربر",
                            RoleName = "user_role"
                        });
                });

            modelBuilder.Entity("RMK.Domain.Models.Account.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 12, 29, 16, 15, 27, 28, DateTimeKind.Local).AddTicks(517),
                            IsDelete = false,
                            LastUpdateDate = new DateTime(2023, 12, 29, 16, 15, 27, 28, DateTimeKind.Local).AddTicks(534),
                            Password = "123",
                            RoleId = 1,
                            UserName = "Saeed"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 12, 29, 16, 15, 27, 28, DateTimeKind.Local).AddTicks(537),
                            IsDelete = false,
                            LastUpdateDate = new DateTime(2023, 12, 29, 16, 15, 27, 28, DateTimeKind.Local).AddTicks(539),
                            Password = "123",
                            RoleId = 1,
                            UserName = "Akbari"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 12, 29, 16, 15, 27, 28, DateTimeKind.Local).AddTicks(541),
                            IsDelete = false,
                            LastUpdateDate = new DateTime(2023, 12, 29, 16, 15, 27, 28, DateTimeKind.Local).AddTicks(543),
                            Password = "123",
                            RoleId = 2,
                            UserName = "Karbar"
                        });
                });

            modelBuilder.Entity("RMK.Domain.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Tehran",
                            PersonId = 1,
                            Street = "Rey"
                        },
                        new
                        {
                            Id = 2,
                            City = "Tehran1",
                            PersonId = 1,
                            Street = "Rey1"
                        },
                        new
                        {
                            Id = 3,
                            City = "Tehran2",
                            PersonId = 2,
                            Street = "Rey2"
                        });
                });

            modelBuilder.Entity("RMK.Domain.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("FullName");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Test1"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Test2"
                        });
                });

            modelBuilder.Entity("RMK.Domain.Models.Account.User", b =>
                {
                    b.HasOne("RMK.Domain.Models.Account.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RMK.Domain.Models.Address", b =>
                {
                    b.HasOne("RMK.Domain.Models.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RMK.Domain.Models.Account.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RMK.Domain.Models.Person", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
